name: Build & Publish Wheels

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            cibw_build: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          - os: ubuntu-24.04
            cibw_build: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          - os: windows-2019
            cibw_build: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          - os: windows-2022
            cibw_build: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          - os: macos-13
            cibw_build: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          - os: macos-14
            cibw_build: "cp310-* cp311-*"
          - os: macos-15
            cibw_build: "cp310-* cp311-*"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_build }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Merge all wheels
        run: |
          mkdir -p final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: final_dist